stages:
  - build
  - deploy

variables:
  IMAGE: node:lts-alpine3.13
  GCLOUD_PROJECT_ID: "myika-anastasia"

frontend-build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH == "master"'
  image: $IMAGE
  script:
    - npm install
    - npm run-script build

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$GCLOUD_ACC_KEY
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud builds submit --tag gcr.io/$GCLOUD_PROJECT_ID/console-$CI_COMMIT_SHORT_SHA
    - gcloud beta run deploy console --image gcr.io/$GCLOUD_PROJECT_ID/console-$CI_COMMIT_SHORT_SHA --port 3000 --platform managed --min-instances 0 --allow-unauthenticated --region asia-southeast1 --memory 128Mi --cpu 1 --concurrency 20
